[book]
authors = ["emreaslan"]
language = "en"
src = "content"
title = "software"
description = "deep notes about software engineering, architectures, and autonomous systems"

# uses KaTeX instead of MathJax, much better interop (client-side via katex-init.js)
#[preprocessor.katex]
#after = ["links"]

# converts mermaid drawings to SVG
[preprocessor.mermaid]
command = "mdbook-mermaid"

# generate table of contents
[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output]

[output.html]
additional-css = ["./utilities/custom.css", "./utilities/katex/katex.min.css"]
additional-js = ["./utilities/mermaid.min.js", "./utilities/mermaid-init.js", "./utilities/toc.js", "./utilities/marked.min.js","./utilities/katex/katex.min.js","./utilities/katex/autorender.min.js","./utilities/katex-init.js"]
git-repository-url = "https://github.com/emreaslan7/software"
git-repository-icon = "fab-github"
no-section-label = true
default-theme = "rust"
