name: Deploy mdBook to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install mdBook and preprocessors
        uses: taiki-e/install-action@v2
        with:
          tool: mdbook,mdbook-mermaid,mdbook-toc

      - name: Build mdBook
        run: mdbook build

      - name: Set up Custom Domain (CNAME)
        run: echo "software.emreaslan.dev" > book/CNAME

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./book

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
